apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-log4j
spec:
  selector:
    matchLabels:
      app: springboot-log4j
  template:
    metadata:
      labels:
        app: springboot-log4j
    spec:
      containers:
      - name: springboot-log4j
        image: ghcr.io/jlandowner/springboot-log4j:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-log4j
spec:
  selector:
    app: springboot-log4j
  ports:
  - port: 8080
    targetPort: 8080
